apiVersion: apps/v1
kind: Deployment
metadata:
  name: seer-ui
spec:
  selector:
    matchLabels:
      app: seer-ui
      tier: frontend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: seer-ui
        tier: frontend
        track: stable
    spec:
      containers:
      - name: ui
        image: "karthicksndr/seer-ui:4"
        ports:
        - name: http
          containerPort: 3000
        stdin: true
        stdinOnce: true
        tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: seer-frontend
spec:
  selector:
    app: seer-ui
  ports:
  - protocol: TCP
    port: 3000